# -*- coding: utf-8 -*-
# """Copy_newIOT_respiscope.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1swign1rmoxA0LUHDfkIK5ACDjJDd5Cfz
# """

# ============================================================
# CELL 1: Install Dependencies
# ============================================================
# !pip install torch torchaudio librosa numpy scikit-learn tqdm --quiet

# ============================================================
# CELL 2: Imports
# ============================================================
import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchaudio
import torchaudio.transforms as T
from sklearn.metrics import classification_report, accuracy_score
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("✅ All imports successful.")
print(f"PyTorch version : {torch.__version__}")
print(f"Torchaudio ver  : {torchaudio.__version__}")
print(f"CUDA available  : {torch.cuda.is_available()}")

# ============================================================
# CELL 3: Global Configuration
# ============================================================
CONFIG = {
    "sample_rate"  : 16000,       # Hz — resample all audio to this rate
    "duration"     : 3,           # seconds per clip
    "num_samples"  : 16000 * 5,   # total samples per clip (80,000)
    "batch_size"   : 2,
    "epochs"       : 15,
    "lr"           : 1e-3,
    "num_type_cls" : 2,           # Heart=0, Lung=1
    "num_cond_cls" : 4,           # Normal=0, Asthma=1, Pneumonia=2, HeartAbnormal=3
    "tcn_channels" : [64, 128, 128, 256],
    "kernel_size"  : 3,
    "dropout"      : 0.2,
    "device"       : "cuda" if torch.cuda.is_available() else "cpu",
}

# Label mapping — (sound_type, condition)
# sound_type : 0=Heart, 1=Lung
# condition  : 0=Normal, 1=Asthma, 2=Pneumonia, 3=HeartAbnormal
LABEL_MAP = {
    "lung_healthy"   : (1, 0),
    "lung_asthma"    : (1, 1),
    "lung_pneumonia" : (1, 2),
    "heart_normal"   : (0, 0),
    "heart_abnormal" : (0, 3),
}

TYPE_NAMES = {0: "Heart", 1: "Lung"}
COND_NAMES = {0: "Normal", 1: "Asthma", 2: "Pneumonia", 3: "Heart Abnormal"}

print("✅ Configuration set.")
print(f"   Device        : {CONFIG['device']}")
print(f"   Sample Rate   : {CONFIG['sample_rate']} Hz")
print(f"   Clip Duration : {CONFIG['duration']} sec  →  {CONFIG['num_samples']} samples")

# ============================================================
# CELL 4: Mount Google Drive
# ============================================================
# from google.colab import drive
# drive.mount("/content/drive", force_remount=True)
print("✅ Google Drive mounted at /content/drive")

# ============================================================
# CELL 5: Dataset Path Handling
# ============================================================
# ⚠️  UPDATE this path to where your 'dataset' folder lives in Drive
DATASET_ROOT = "/content/drive/MyDrive/dataset"

# Sub-folder definitions
TRAIN_FOLDERS = [
    os.path.join(DATASET_ROOT, "lung-sound", "lung-train"),
    os.path.join(DATASET_ROOT, "heart-sound", "heart-train"),
]
TEST_FOLDERS = [
    os.path.join(DATASET_ROOT, "lung-sound", "lung-test"),
    os.path.join(DATASET_ROOT, "heart-sound", "heart-test"),
]

# Sanity check
print("📂 Verifying dataset paths ...\n")
for folder in TRAIN_FOLDERS + TEST_FOLDERS:
    exists = os.path.isdir(folder)
    status = "✅" if exists else "❌ MISSING"
    print(f"  {status}  {folder}")
    if exists:
        sub = [d for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d))]
        for s in sub:
            count = len([
                f for f in os.listdir(os.path.join(folder, s))
                if f.endswith(".wav")
            ])
            print(f"           └─ {s:25s}  ({count} .wav files)")

# ============================================================
# CELL 6: Audio Loading — load, resample, normalize, pad/trim
# ============================================================
def load_audio(file_path: str, config: dict) -> torch.Tensor:
    """
    Load a .wav file and return a fixed-length, mono, normalized waveform.

    Steps:
      1. Load with torchaudio (handles most formats)
      2. Convert to mono by averaging channels
      3. Resample to CONFIG['sample_rate']
      4. Trim or pad to CONFIG['num_samples']
      5. Peak-normalize to [-1, 1]

    Returns:
      waveform : Tensor of shape (1, num_samples)
    """
    try:
        import librosa
        import numpy as np
        # 1. Load with librosa (handles most formats, robust fallback)
        # 2. Convert to mono natively
        # 3. Resample to CONFIG['sample_rate'] natively
        y, sr = librosa.load(file_path, sr=config["sample_rate"], mono=True)
        waveform = torch.from_numpy(y).unsqueeze(0)
    except Exception as e:
        raise RuntimeError(f"Failed to load {file_path}: {e}")

    # Step 4 — trim / pad
    target = config["num_samples"]
    length = waveform.shape[1]
    if length > target:
        waveform = waveform[:, :target]
    elif length < target:
        pad_size = target - length
        waveform = torch.nn.functional.pad(waveform, (0, pad_size))

    # Step 5 — peak normalize
    peak = waveform.abs().max()
    if peak > 0:
        waveform = waveform / peak

    return waveform   # shape: (1, num_samples)


print("✅ Audio loading utility defined.")

# ============================================================
# CELL 7: Data Augmentation (raw waveform only)
# ============================================================
def add_noise(waveform: torch.Tensor, noise_level: float = 0.005) -> torch.Tensor:
    """Add Gaussian white noise."""
    noise = torch.randn_like(waveform) * noise_level
    return (waveform + noise).clamp(-1.0, 1.0)


def time_shift(waveform: torch.Tensor, max_shift_ratio: float = 0.1) -> torch.Tensor:
    """Randomly shift waveform left or right (circular roll)."""
    shift = int(random.uniform(-max_shift_ratio, max_shift_ratio) * waveform.shape[1])
    return torch.roll(waveform, shifts=shift, dims=1)


def time_stretch(waveform: torch.Tensor, rate_range: tuple = (0.9, 1.1)) -> torch.Tensor:
    """
    Approximate time-stretch by resampling at a slightly different rate
    then trimming/padding back to the original length.
    Avoids spectrogram computation — keeps everything in raw waveform domain.
    """
    rate        = random.uniform(*rate_range)
    orig_len    = waveform.shape[1]
    new_len     = int(orig_len * rate)

    # Interpolate (1D linear) to new_len
    wav_np      = waveform.numpy()                          # (1, orig_len)
    x_old       = np.linspace(0, 1, orig_len)
    x_new       = np.linspace(0, 1, new_len)
    stretched   = np.interp(x_new, x_old, wav_np[0])       # (new_len,)
    stretched   = torch.tensor(stretched, dtype=torch.float32).unsqueeze(0)  # (1, new_len)

    # Re-trim or pad to original length
    if new_len > orig_len:
        stretched = stretched[:, :orig_len]
    else:
        pad_size  = orig_len - new_len
        stretched = torch.nn.functional.pad(stretched, (0, pad_size))

    return stretched


def augment(waveform: torch.Tensor, apply_prob: float = 0.5) -> torch.Tensor:
    """Apply each augmentation independently with probability `apply_prob`."""
    if random.random() < apply_prob:
        waveform = add_noise(waveform)
    if random.random() < apply_prob:
        waveform = time_shift(waveform)
    if random.random() < apply_prob:
        waveform = time_stretch(waveform)
    return waveform


print("✅ Augmentation utilities defined.")

# ============================================================
# CELL 8: Custom Dataset Class (FINAL FIXED VERSION)
# ============================================================
class RespiScopeDataset(Dataset):
    def __init__(self, root_folders, config, augment_data=False):
        self.config = config
        self.augment_data = augment_data
        self.samples = []   # (file_path, type_label, condition_label)

        self._scan_folders(root_folders)

        print(f"✅ Total samples loaded: {len(self.samples)}")
        print("🔍 Sample entries:", self.samples[:5])

    def _scan_folders(self, root_folders):
        for root in root_folders:
            if not os.path.isdir(root):
                print(f"⚠️ Skipping missing folder: {root}")
                continue

            root_lower = root.lower()

            for class_dir in sorted(os.listdir(root)):
                class_path = os.path.join(root, class_dir)

                if not os.path.isdir(class_path):
                    continue

                folder_name = class_dir.lower()

                # =========================
                # 🔥 LABEL MAPPING LOGIC
                # =========================
                if "lung-sound" in root_lower:
                    type_lbl = 1
                    if folder_name == "healthy":
                        cond_lbl = 0
                    elif folder_name == "asthma":
                        cond_lbl = 1
                    elif folder_name == "pneumonia":
                        cond_lbl = 2
                    else:
                        print(f"⚠️ Unknown lung class '{folder_name}' — skipping.")
                        continue

                elif "heart-sound" in root_lower:
                    type_lbl = 0
                    if folder_name == "normal":
                        cond_lbl = 0
                    elif folder_name == "abnormal":
                        cond_lbl = 3
                    else:
                        print(f"⚠️ Unknown heart class '{folder_name}' — skipping.")
                        continue

                else:
                    print(f"⚠️ Unknown root folder '{root}' — skipping.")
                    continue

                # =========================
                # Collect WAV files
                # =========================
                wav_files = [
                    os.path.join(class_path, f)
                    for f in os.listdir(class_path)
                    if f.lower().endswith(".wav")
                ]

                if len(wav_files) == 0:
                    print(f"⚠️ No .wav files in {class_path}")

                for wav in wav_files:
                    self.samples.append((wav, type_lbl, cond_lbl))

        if len(self.samples) == 0:
            raise RuntimeError("❌ No .wav files found! Check dataset path.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        file_path, type_lbl, cond_lbl = self.samples[idx]

        waveform = load_audio(file_path, self.config)  # (1, num_samples)

        if self.augment_data:
            waveform = augment(waveform)

        return (
            waveform,
            torch.tensor(type_lbl, dtype=torch.long),
            torch.tensor(cond_lbl, dtype=torch.long),
        )

print("✅ RespiScopeDataset class ready.")

# ============================================================
# CELL 9: Debug — folder structure & sample counts
# ============================================================
def debug_dataset(root_folders, label_map=LABEL_MAP):
    return
    print("=" * 55)
    print("  DATASET DEBUG REPORT")
    print("=" * 55)
    total = 0
    class_counts = {}

    for root in root_folders:
        print(f"\n📂 {root}")
        if not os.path.isdir(root):
            print("   ❌ Directory does NOT exist!")
            continue
        for class_dir in sorted(os.listdir(root)):
            class_path = os.path.join(root, class_dir)
            if not os.path.isdir(class_path):
                continue
            wav_files = [f for f in os.listdir(class_path) if f.lower().endswith(".wav")]
            count     = len(wav_files)
            total    += count
            label     = label_map.get(class_dir, "⚠️  UNKNOWN")
            class_counts[class_dir] = class_counts.get(class_dir, 0) + count
            print(f"   ├─ {class_dir:25s}  label={label}   files={count}")

    print(f"\n{'─'*55}")
    print(f"  Total .wav files found : {total}")
    print(f"{'─'*55}")
    print("\nPer-class totals (across all splits):")
    for cls, cnt in sorted(class_counts.items()):
        print(f"  {cls:25s} : {cnt}")
    print("=" * 55)

# Run on both train and test
# debug_dataset(TRAIN_FOLDERS + TEST_FOLDERS)

# ============================================================
# CELL 10: Build DataLoaders
# ============================================================
# train_dataset = RespiScopeDataset(
# #     root_folders  = TRAIN_FOLDERS,
# #     config        = CONFIG,
# #     augment_data  = True,
# # )
# # 
# # test_dataset = RespiScopeDataset(
# # #     root_folders  = TEST_FOLDERS,
# # #     config        = CONFIG,
# # #     augment_data  = False,
# # # )
# # # 
# # # train_loader = DataLoader(
# # # #     train_dataset,
# # # #     batch_size  = CONFIG["batch_size"],
# # # #     shuffle     = True,
# # # #     num_workers = 2,
# # # #     pin_memory  = CONFIG["device"] == "cuda",
# # # #     drop_last   = False,
# # # # )
# # # 
# # # # test_loader = DataLoader(
# # #     test_dataset,
# # #     batch_size  = CONFIG["batch_size"],
# # #     shuffle     = False,
# # #     num_workers = 2,
# # #     pin_memory  = CONFIG["device"] == "cuda",
# # #     drop_last   = False,
# # # )
# # 
# # print(f"✅ DataLoaders ready.")
# # print(f"   Train samples : {len(train_dataset)}")
# # print(f"   Test  samples : {len(test_dataset)}")
# # print(f"   Train batches : {len(train_loader)}")
# # print(f"   Test  batches : {len(test_loader)}")
# # 
# # # Verify a batch shape
# # # batch_wav, batch_type, batch_cond = next(iter(train_loader))
# # print(f"\n   Sample batch  :")
# # # waveform print removed
# # # type_lbl print removed
# cond_lbl print removed

# ============================================================
# CELL 11: Temporal Convolutional Network (TCN)
# ============================================================

# ── Residual Block ────────────────────────────────────────────
class TCNResidualBlock(nn.Module):
    """
    One TCN residual block:
      Conv1d (dilated) → BatchNorm → ReLU → Dropout
      Conv1d (dilated) → BatchNorm → ReLU → Dropout
      + residual (1×1 conv if channel mismatch)
    """
    def __init__(self, in_channels, out_channels, kernel_size, dilation, dropout):
        super().__init__()
        # Same-padding for causal / symmetric convolution
        padding = (kernel_size - 1) * dilation // 2

        self.conv1 = nn.Conv1d(
            in_channels, out_channels,
            kernel_size=kernel_size,
            dilation=dilation,
            padding=padding,
        )
        self.bn1      = nn.BatchNorm1d(out_channels)
        self.relu1    = nn.ReLU()
        self.drop1    = nn.Dropout(dropout)

        self.conv2 = nn.Conv1d(
            out_channels, out_channels,
            kernel_size=kernel_size,
            dilation=dilation,
            padding=padding,
        )
        self.bn2      = nn.BatchNorm1d(out_channels)
        self.relu2    = nn.ReLU()
        self.drop2    = nn.Dropout(dropout)

        # 1×1 projection for residual if channels differ
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, kernel_size=1)
            if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x):
        residual = self.residual_conv(x)

        out = self.drop1(self.relu1(self.bn1(self.conv1(x))))
        out = self.drop2(self.relu2(self.bn2(self.conv2(out))))

        # Trim if temporal dimension drifted (safety guard)
        if out.shape[-1] != residual.shape[-1]:
            min_len = min(out.shape[-1], residual.shape[-1])
            out      = out[..., :min_len]
            residual = residual[..., :min_len]

        return out + residual


# ── Full TCN backbone ─────────────────────────────────────────
class TCNBackbone(nn.Module):
    """
    Stack of TCNResidualBlocks with exponentially growing dilation.
    Input  : (B, 1, T)
    Output : (B, channels[-1], T')
    """
    def __init__(self, channels, kernel_size, dropout):
        super().__init__()
        layers = []
        in_ch  = 1
        for i, out_ch in enumerate(channels):
            dilation = 2 ** i        # 1, 2, 4, 8, …
            layers.append(
                TCNResidualBlock(in_ch, out_ch, kernel_size, dilation, dropout)
            )
            in_ch = out_ch
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x)       # (B, channels[-1], T')


# ── Full RespiScope model ─────────────────────────────────────
class RespiScopeModel(nn.Module):
    """
    TCN backbone → Global Average Pooling →
      Head 1 : sound type  (Heart / Lung)
      Head 2 : condition   (Normal / Asthma / Pneumonia / HeartAbnormal)
    """
    def __init__(self, config):
        super().__init__()
        channels    = config["tcn_channels"]
        kernel_size = config["kernel_size"]
        dropout     = config["dropout"]

        self.backbone = TCNBackbone(channels, kernel_size, dropout)

        feat_dim = channels[-1]
        self.pool = nn.AdaptiveAvgPool1d(1)   # (B, feat_dim, 1)

        # Head 1 — sound type
        self.head_type = nn.Sequential(
            nn.Linear(feat_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, config["num_type_cls"]),
        )

        # Head 2 — condition
        self.head_cond = nn.Sequential(
            nn.Linear(feat_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, config["num_cond_cls"]),
        )

    def forward(self, x):
        # x : (B, 1, T)
        features   = self.backbone(x)          # (B, C, T')
        pooled     = self.pool(features)        # (B, C, 1)
        pooled     = pooled.squeeze(-1)         # (B, C)

        out_type   = self.head_type(pooled)     # (B, num_type_cls)
        out_cond   = self.head_cond(pooled)     # (B, num_cond_cls)

        return out_type, out_cond


print("✅ TCN model classes defined.")

# ============================================================
